name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: bash ./gradlew assembleRelease
    - name: Upload built apk
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: Killergram
        path: ${{ github.workspace }}/app/build/outputs/apk/release
