name: Release Build
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: bash ./gradlew assembleRelease
      - name: Checking release version
        id: version
        run: |
          echo ::set-output name=release_version::$(cat gradle.properties | grep appVerName | awk -F'=' '{print $2}')
      - name: Delete tag if exists
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: ${{ steps.version.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag Release
        uses: richardsimko/update-tag@v1.0.7
        with:
          tag_name: ${{ steps.version.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: ${{ steps.version.outputs.release_version }}
          files: ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
          draft: false
          generate_release_notes: true
